### ISSUE TITLE
Task A4.3-b Implement a Support page

### ISSUE THREAD

**Issue by salparram** [gii-is-psg2/psg2-2122-g7-76#80]

**Comment by Juangr4** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-2122-G7-76-S4-62334b4c95547100109f92ce/issues/gii-is-psg2/psg2-2122-g7-76/80?planning-poker) with ZenHub @erngutcon @fravilpav @romflorod @salparram
